name: Maven Package

on: [pull_request]

jobs:
  package:
    name: Package with JDK ${{ matrix.jdk_version }}

    strategy:
      matrix:
        jdk_version: [11, 12, 13]
        mvn_action: [package]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.jdk_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk_version }}

      - name: Maven ${{ matrix.mvn_action }}
        run: |
          mvn --file pom.xml \
              -Dspring.config.location=.github/application.yml \
              ${{ matrix.mvn_action }}
